DROP TABLE IF EXISTS SYS_PRJ_PMSN;
DROP TABLE IF EXISTS SYS_ROLE_PMSN;
DROP TABLE IF EXISTS SYS_PRJ_USER;
DROP TABLE IF EXISTS SYS_USER_PMSN;
DROP TABLE IF EXISTS SYS_POST_ROLE;
DROP TABLE IF EXISTS SYS_USER_ROLE;
DROP TABLE IF EXISTS SYS_USER_POST;
DROP TABLE IF EXISTS SYS_PERMISSION;
DROP TABLE IF EXISTS SYS_PROJECT;
DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_USER;
DROP TABLE IF EXISTS SYS_POST;
DROP TABLE IF EXISTS SYS_DIVISION;
DROP TABLE IF EXISTS SYS_COMPANY;

-- ----------------------------
-- 权限表 SYS_PERMISSION
-- ----------------------------
CREATE TABLE SYS_PERMISSION (
  PMSN_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '权限自增ID',
  PMSN_NAME varchar(100) DEFAULT NULL COMMENT '权限名称',
	PRNT_ID int(11) DEFAULT NULL COMMENT '父权限ID',
	PRNT_NAME varchar(100) DEFAULT NULL COMMENT '父权限名称',
	PMSN_CODE varchar(100) NOT NULL COMMENT '权限标识',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
	TYPE char(1) NOT NULL DEFAULT 'M' COMMENT '权限类型,M:菜单,O:操作',
	STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
	PMSN_URL varchar(500) DEFAULT NULL COMMENT '权限对应URL',
	PMSN_ICON varchar(100) DEFAULT NULL COMMENT '图标',
	PMSN_DESC varchar(500) DEFAULT NULL COMMENT '权限描述',
	IS_LEAF char(1) NOT NULL DEFAULT 'Y' COMMENT '是否叶节点,Y是N否',
	CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
	IS_DEFAULT char(1) NOT NULL DEFAULT 'N' COMMENT '是否默认权限，Y是N否',
  PRIMARY KEY (PMSN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='权限表';

-- ----------------------------
-- 项目组表 SYS_PROJECT
-- ----------------------------
CREATE TABLE SYS_PROJECT (
  PRJ_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目自增ID',
  PRJ_NAME varchar(100) NOT NULL COMMENT '项目名称',
  PRJ_DESC varchar(500) DEFAULT NULL COMMENT '项目描述',
  LEADER int(11) NOT NULL COMMENT '项目领导',
	LEVEL  int(11) NOT NULL DEFAULT 1 COMMENT '项目等级(可扩展为外键)',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PRJ_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组表';

-- ----------------------------
-- 角色表 SYS_ROLE
-- ----------------------------
CREATE TABLE SYS_ROLE (
  ROLE_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '角色自增ID',
  ROLE_NAME varchar(100) NOT NULL COMMENT '角色名称',
  ROLE_DESC varchar(500) DEFAULT NULL COMMENT '角色描述',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='角色表';

-- ----------------------------
-- 用户表 SYS_USER
-- ----------------------------
CREATE TABLE SYS_USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户自增ID',
  USER_NAME varchar(20) DEFAULT NULL COMMENT '用户名称',
  ACCOUNT varchar(20) NOT NULL COMMENT '用户账号',
  POST_ID int(11) DEFAULT NULL COMMENT '岗位编号',
  DIV_ID int(11) DEFAULT NULL COMMENT '组织部门编号',
  PASSWORD varchar(100) DEFAULT NULL COMMENT '密码',
  EMAIL varchar(200) DEFAULT NULL COMMENT '电子邮箱',
	PHONE varchar(20) DEFAULT NULL COMMENT '用户电话',
  FIRST_LOGIN datetime DEFAULT NULL COMMENT '第一次登录',
  PREV_LOGIN datetime DEFAULT NULL COMMENT '上一次登录',
	PREV_IP varchar(20) DEFAULT NULL COMMENT '上一次登录IP地址',
  LAST_LOGIN datetime DEFAULT NULL COMMENT '最后一次登录',
  LOGIN_COUNT int(11) DEFAULT NULL COMMENT '登录次数',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  USER_DESC varchar(500) DEFAULT NULL COMMENT '备注',
  IS_ONLINE int(1) DEFAULT NULL COMMENT '是否在线',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
	PRIMARY KEY (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- ----------------------------
-- 岗位表 SYS_POST
-- ----------------------------
CREATE TABLE SYS_POST (
  POST_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '岗位自增ID',
  POST_NAME varchar(100) DEFAULT NULL COMMENT '岗位名称',
  DIV_ID int(11) NOT NULL COMMENT '部门ID',
	POST_DESC varchar(500) DEFAULT NULL COMMENT '备注',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (POST_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='岗位表';

-- ----------------------------
-- 组织部门表 SYS_DIVISION
-- ----------------------------
CREATE TABLE SYS_DIVISION (
  DIV_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '部门自增ID',
  DIV_NAME varchar(100) DEFAULT NULL COMMENT '部门名称',
  MANAGER int(11) DEFAULT NULL COMMENT '部门领导对应的USERID',
  DIV_PHONE varchar(50) DEFAULT NULL COMMENT '部门电话',
	PRNT_ID int(11) DEFAULT NULL COMMENT '父部门ID',
  DIV_ADR varchar(500) DEFAULT NULL COMMENT '部门地址',
	CO_ID int(11) NOT NULL COMMENT '所属公司ID',
  DIV_DESC varchar(500) DEFAULT NULL COMMENT '备注',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  DIV_ICON varchar(100) DEFAULT NULL COMMENT '图标',
  PRIMARY KEY (DIV_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='组织部门表';

-- ----------------------------
-- 公司表 SYS_COMPANY
-- ----------------------------
CREATE TABLE SYS_COMPANY (
  CO_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '公司自增ID',
  CO_NAME varchar(100) DEFAULT NULL COMMENT '公司名称',
  CO_PHONE varchar(20) DEFAULT NULL COMMENT '公司电话',
  CO_FAX varchar(20) DEFAULT NULL COMMENT '公司传真',
  CO_ADR varchar(500) DEFAULT NULL COMMENT '公司地址',
  ZIP varchar(10) DEFAULT NULL COMMENT '邮政编码',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
  EMAIL varchar(100) DEFAULT NULL COMMENT '公司邮件地址',
  CONTACT varchar(100) DEFAULT NULL COMMENT '公司联络人',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  MANAGER varchar(100) DEFAULT NULL COMMENT '公司负责人',
  BANK varchar(100) DEFAULT NULL COMMENT '开户行',
  BANK_ACCT varchar(100) DEFAULT NULL COMMENT '银行账号',
  CO_DESC varchar(500) DEFAULT NULL COMMENT '备注',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (CO_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='公司表';

-- ----------------------------
-- 权限角色表 SYS_ROLE_PMSN
-- ----------------------------
CREATE TABLE SYS_ROLE_PMSN (
  RP_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '权限角色配置自增ID',
  ROLE_ID int(11) NOT NULL COMMENT '角色ID',
	PMSN_ID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (RP_ID),
	KEY FK_RP_ROLE (ROLE_ID),
  KEY FK_RP_PMSN (PMSN_ID),
  CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID),
  CONSTRAINT FK_RP_PMSN FOREIGN KEY (PMSN_ID) REFERENCES SYS_PERMISSION (PMSN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='权限角色表';

-- ----------------------------
-- 项目组权限表 SYS_PRJ_PMSN
-- ----------------------------
CREATE TABLE SYS_PRJ_PMSN (
  PP_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目组权限配置自增ID',
  PRJ_ID int(11) NOT NULL COMMENT '项目组ID',
	PMSN_ID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PP_ID),
	KEY FK_PP_PRJ (PRJ_ID),
  KEY FK_PP_PMSN (PMSN_ID),
  CONSTRAINT FK_PP_PRJ FOREIGN KEY (PRJ_ID) REFERENCES SYS_PROJECT (PRJ_ID),
  CONSTRAINT FK_PP_PMSN FOREIGN KEY (PMSN_ID) REFERENCES SYS_PERMISSION (PMSN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组权限表';

-- ----------------------------
-- 项目组成员表 SYS_PRJ_USER
-- ----------------------------
CREATE TABLE SYS_PRJ_USER (
	PU_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目成员配置自增ID',
  PRJ_ID int(11) NOT NULL COMMENT '项目组ID',
	USER_ID int(11) NOT NULL COMMENT '用户ID',
	LEADER char(1) NOT NULL DEFAULT 'N' COMMENT '是否组长,Y是N否',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PU_ID),
	KEY FK_PU_PRJ (PRJ_ID),
  KEY FK_PU_USER (USER_ID),
  CONSTRAINT FK_PU_PRJ FOREIGN KEY (PRJ_ID) REFERENCES SYS_PROJECT (PRJ_ID),
  CONSTRAINT FK_PU_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组成员表';

-- ----------------------------
-- 用户角色表 SYS_USER_ROLE
-- ----------------------------
CREATE TABLE SYS_USER_ROLE (
  UR_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户角色配置自增ID',
  ROLE_ID int(11) NOT NULL COMMENT '角色ID',
	USER_ID int(11) NOT NULL COMMENT '用户ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (UR_ID),
	KEY FK_UR_ROLE (ROLE_ID),
  KEY FK_UR_USER (USER_ID),
  CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID),
  CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户角色表';

-- ----------------------------
-- 用户岗位表 SYS_USER_POST
-- ----------------------------
CREATE TABLE SYS_USER_POST (
  UP_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户岗位配置自增ID',
  USER_ID int(11) NOT NULL COMMENT '角色ID',
	POST_ID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (UP_ID),
	KEY FK_UP_USER (USER_ID),
  KEY FK_UP_POST (POST_ID),
  CONSTRAINT FK_UP_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
  CONSTRAINT FK_UP_POST FOREIGN KEY (POST_ID) REFERENCES SYS_POST (POST_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户岗位表';

-- ----------------------------
-- 岗位角色表 SYS_POST_ROLE
-- ----------------------------
CREATE TABLE SYS_POST_ROLE (
  PR_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '岗位角色配置自增ID',
  ROLE_ID int(11) NOT NULL COMMENT '角色ID',
	POST_ID int(11) NOT NULL COMMENT '岗位ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PR_ID),
	KEY FK_PR_ROLE (ROLE_ID),
  KEY FK_PR_POST (POST_ID),
  CONSTRAINT FK_PR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID),
  CONSTRAINT FK_PR_POST FOREIGN KEY (POST_ID) REFERENCES SYS_POST (POST_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='岗位角色表';

-- ----------------------------
-- 用户权限表 SYS_USER_PMSN
-- ----------------------------
CREATE TABLE SYS_USER_PMSN (
  UPM_ID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户权限配置自增ID',
  USER_ID int(11) NOT NULL COMMENT '用户ID',
	PMSN_ID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (UPM_ID),
	KEY FK_UPM_USER (USER_ID),
  KEY FK_UPM_PMSN (PMSN_ID),
  CONSTRAINT FK_UPM_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
  CONSTRAINT FK_UPM_PMSN FOREIGN KEY (PMSN_ID) REFERENCES SYS_PERMISSION (PMSN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户权限表';