DROP TABLE IF EXISTS SYS_PRJ_PMSN;
DROP TABLE IF EXISTS SYS_ROLE_PMSN;
DROP TABLE IF EXISTS SYS_PRJ_USER;
DROP TABLE IF EXISTS SYS_USER_PMSN;
DROP TABLE IF EXISTS SYS_POST_ROLE;
DROP TABLE IF EXISTS SYS_USER_ROLE;
DROP TABLE IF EXISTS SYS_USER_POST;
DROP TABLE IF EXISTS SYS_PERMISSION;
DROP TABLE IF EXISTS SYS_PROJECT;
DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_USER;
DROP TABLE IF EXISTS SYS_POST;
DROP TABLE IF EXISTS SYS_DIVISION;
DROP TABLE IF EXISTS SYS_COMPANY;

-- ----------------------------
-- 权限表 SYS_PERMISSION
-- ----------------------------
CREATE TABLE SYS_PERMISSION (
  PMSNID int(11) NOT NULL AUTO_INCREMENT COMMENT '权限自增ID',
  PMSNNAME varchar(100) DEFAULT NULL COMMENT '权限名称',
	PRNTID int(11) DEFAULT NULL COMMENT '父权限ID',
	PRNTNAME varchar(100) DEFAULT NULL COMMENT '父权限名称',
	PMSNCODE varchar(100) NOT NULL COMMENT '权限标识',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
	TYPE char(1) NOT NULL DEFAULT 'M' COMMENT '权限类型,M:菜单,O:操作',
	STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
	PMSNURL varchar(500) DEFAULT NULL COMMENT '权限对应URL',
	PMSNICON varchar(100) DEFAULT NULL COMMENT '图标',
	PMSNDESC varchar(500) DEFAULT NULL COMMENT '权限描述',
	ISLEAF char(1) NOT NULL DEFAULT 'Y' COMMENT '是否叶节点,Y是N否',
	CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
	ISDEFAULT char(1) NOT NULL DEFAULT 'N' COMMENT '是否默认权限，Y是N否',
  PRIMARY KEY (PMSNID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='权限表';

-- ----------------------------
-- 项目组表 SYS_PROJECT
-- ----------------------------
CREATE TABLE SYS_PROJECT (
  PRJID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目自增ID',
  PRJNAME varchar(100) NOT NULL COMMENT '项目名称',
  PRJDESC varchar(500) DEFAULT NULL COMMENT '项目描述',
  LEADER int(11) NOT NULL COMMENT '项目领导',
	LEVEL  int(11) NOT NULL DEFAULT 1 COMMENT '项目等级(可扩展为外键)',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PRJID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组表';

-- ----------------------------
-- 角色表 SYS_ROLE
-- ----------------------------
CREATE TABLE SYS_ROLE (
  ROLEID int(11) NOT NULL AUTO_INCREMENT COMMENT '角色自增ID',
  ROLENAME varchar(100) NOT NULL COMMENT '角色名称',
  ROLEDESC varchar(500) DEFAULT NULL COMMENT '角色描述',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (ROLEID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='角色表';

-- ----------------------------
-- 用户表 SYS_USER
-- ----------------------------
CREATE TABLE SYS_USER (
  USERID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户自增ID',
  USERNAME varchar(20) DEFAULT NULL COMMENT '用户名称',
  ACCOUNT varchar(20) NOT NULL COMMENT '用户账号',
  POSTID int(11) DEFAULT NULL COMMENT '岗位编号',
  DIVID int(11) DEFAULT NULL COMMENT '组织部门编号',
  PASSWORD varchar(100) DEFAULT NULL COMMENT '密码',
  EMAIL varchar(200) DEFAULT NULL COMMENT '电子邮箱',
	PHONE varchar(20) DEFAULT NULL COMMENT '用户电话',
  FIRSTLOGIN datetime DEFAULT NULL COMMENT '第一次登录',
  PREVLOGIN datetime DEFAULT NULL COMMENT '上一次登录',
	PREVIP varchar(20) DEFAULT NULL COMMENT '上一次登录IP地址',
  LASTLOGIN datetime DEFAULT NULL COMMENT '最后一次登录',
  LOGINCOUNT int(11) DEFAULT NULL COMMENT '登录次数',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  USERDESC varchar(500) DEFAULT NULL COMMENT '备注',
  ISONLINE int(1) DEFAULT NULL COMMENT '是否在线',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
	PRIMARY KEY (USERID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- ----------------------------
-- 岗位表 SYS_POST
-- ----------------------------
CREATE TABLE SYS_POST (
  POSTID int(11) NOT NULL AUTO_INCREMENT COMMENT '岗位自增ID',
  POSTNAME varchar(100) DEFAULT NULL COMMENT '岗位名称',
  DIVID int(11) NOT NULL COMMENT '部门ID',
	POSTDESC varchar(500) DEFAULT NULL COMMENT '备注',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (POSTID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='岗位表';

-- ----------------------------
-- 组织部门表 SYS_DIVISION
-- ----------------------------
CREATE TABLE SYS_DIVISION (
  DIVID int(11) NOT NULL AUTO_INCREMENT COMMENT '部门自增ID',
  DIVNAME varchar(100) DEFAULT NULL COMMENT '部门名称',
  MANAGER int(11) DEFAULT NULL COMMENT '部门领导对应的USERID',
  DIVPHONE varchar(50) DEFAULT NULL COMMENT '部门电话',
	PRNTID int(11) DEFAULT NULL COMMENT '父部门ID',
  DIVADR varchar(500) DEFAULT NULL COMMENT '部门地址',
	COID int(11) NOT NULL COMMENT '所属公司ID',
  DIVDESC varchar(500) DEFAULT NULL COMMENT '备注',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  DIVICON varchar(100) DEFAULT NULL COMMENT '图标',
  PRIMARY KEY (DIVID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='组织部门表';

-- ----------------------------
-- 公司表 SYS_COMPANY
-- ----------------------------
CREATE TABLE SYS_COMPANY (
  COID int(11) NOT NULL AUTO_INCREMENT COMMENT '公司自增ID',
  CONAME varchar(100) DEFAULT NULL COMMENT '公司名称',
  COPHONE varchar(20) DEFAULT NULL COMMENT '公司电话',
  COFAX varchar(20) DEFAULT NULL COMMENT '公司传真',
  COADR varchar(500) DEFAULT NULL COMMENT '公司地址',
  ZIP varchar(10) DEFAULT NULL COMMENT '邮政编码',
	SORT int(11) DEFAULT NULL COMMENT '排序列',
  EMAIL varchar(100) DEFAULT NULL COMMENT '公司邮件地址',
  CONTACT varchar(100) DEFAULT NULL COMMENT '公司联络人',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  MANAGER varchar(100) DEFAULT NULL COMMENT '公司负责人',
  BANK varchar(100) DEFAULT NULL COMMENT '开户行',
  BANKACCT varchar(100) DEFAULT NULL COMMENT '银行账号',
  CODESC varchar(500) DEFAULT NULL COMMENT '备注',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (COID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='公司表';

-- ----------------------------
-- 权限角色表 SYS_ROLE_PMSN
-- ----------------------------
CREATE TABLE SYS_ROLE_PMSN (
  RPID int(11) NOT NULL AUTO_INCREMENT COMMENT '权限角色配置自增ID',
  ROLEID int(11) NOT NULL COMMENT '角色ID',
	PMSNID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (RPID),
	KEY FK_RP_ROLE (ROLEID),
  KEY FK_RP_PMSN (PMSNID),
  CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLEID) REFERENCES SYS_ROLE (ROLEID),
  CONSTRAINT FK_RP_PMSN FOREIGN KEY (PMSNID) REFERENCES SYS_PERMISSION (PMSNID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='权限角色表';

-- ----------------------------
-- 项目组权限表 SYS_PRJ_PMSN
-- ----------------------------
CREATE TABLE SYS_PRJ_PMSN (
  PPID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目组权限配置自增ID',
  PRJID int(11) NOT NULL COMMENT '项目组ID',
	PMSNID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PPID),
	KEY FK_PP_PRJ (PRJID),
  KEY FK_PP_PMSN (PMSNID),
  CONSTRAINT FK_PP_PRJ FOREIGN KEY (PRJID) REFERENCES SYS_PROJECT (PRJID),
  CONSTRAINT FK_PP_PMSN FOREIGN KEY (PMSNID) REFERENCES SYS_PERMISSION (PMSNID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组权限表';

-- ----------------------------
-- 项目组成员表 SYS_PRJ_USER
-- ----------------------------
CREATE TABLE SYS_PRJ_USER (
	PUID int(11) NOT NULL AUTO_INCREMENT COMMENT '项目成员配置自增ID',
  PRJID int(11) NOT NULL COMMENT '项目组ID',
	USERID int(11) NOT NULL COMMENT '用户ID',
	LEADER char(1) NOT NULL DEFAULT 'N' COMMENT '是否组长,Y是N否',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PUID),
	KEY FK_PU_PRJ (PRJID),
  KEY FK_PU_USER (USERID),
  CONSTRAINT FK_PU_PRJ FOREIGN KEY (PRJID) REFERENCES SYS_PROJECT (PRJID),
  CONSTRAINT FK_PU_USER FOREIGN KEY (USERID) REFERENCES SYS_USER (USERID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='项目组成员表';

-- ----------------------------
-- 用户角色表 SYS_USER_ROLE
-- ----------------------------
CREATE TABLE SYS_USER_ROLE (
  URID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户角色配置自增ID',
  ROLEID int(11) NOT NULL COMMENT '角色ID',
	USERID int(11) NOT NULL COMMENT '用户ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (URID),
	KEY FK_UR_ROLE (ROLEID),
  KEY FK_UR_USER (USERID),
  CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLEID) REFERENCES SYS_ROLE (ROLEID),
  CONSTRAINT FK_UR_USER FOREIGN KEY (USERID) REFERENCES SYS_USER (USERID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户角色表';

-- ----------------------------
-- 用户岗位表 SYS_USER_POST
-- ----------------------------
CREATE TABLE SYS_USER_POST (
  UPID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户岗位配置自增ID',
  USERID int(11) NOT NULL COMMENT '角色ID',
	POSTID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (UPID),
	KEY FK_UP_USER (USERID),
  KEY FK_UP_POST (POSTID),
  CONSTRAINT FK_UP_USER FOREIGN KEY (USERID) REFERENCES SYS_USER (USERID),
  CONSTRAINT FK_UP_POST FOREIGN KEY (POSTID) REFERENCES SYS_POST (POSTID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户岗位表';

-- ----------------------------
-- 岗位角色表 SYS_POST_ROLE
-- ----------------------------
CREATE TABLE SYS_POST_ROLE (
  PRID int(11) NOT NULL AUTO_INCREMENT COMMENT '岗位角色配置自增ID',
  ROLEID int(11) NOT NULL COMMENT '角色ID',
	POSTID int(11) NOT NULL COMMENT '岗位ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (PRID),
	KEY FK_PR_ROLE (ROLEID),
  KEY FK_PR_POST (POSTID),
  CONSTRAINT FK_PR_ROLE FOREIGN KEY (ROLEID) REFERENCES SYS_ROLE (ROLEID),
  CONSTRAINT FK_PR_POST FOREIGN KEY (POSTID) REFERENCES SYS_POST (POSTID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='岗位角色表';

-- ----------------------------
-- 用户权限表 SYS_USER_PMSN
-- ----------------------------
CREATE TABLE SYS_USER_PMSN (
  UPMID int(11) NOT NULL AUTO_INCREMENT COMMENT '用户权限配置自增ID',
  USERID int(11) NOT NULL COMMENT '用户ID',
	PMSNID int(11) NOT NULL COMMENT '权限ID',
  STATUS char(1) NOT NULL DEFAULT 'E' COMMENT '当前状态,E:有效的,I:无效的',
  CREATED datetime DEFAULT NULL COMMENT '创造日期',
  LASTMOD datetime DEFAULT NULL COMMENT '修改日期',
  CREATER int(11) DEFAULT NULL COMMENT '创建人',
  MODIFYER int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (UPMID),
	KEY FK_UPM_USER (USERID),
  KEY FK_UPM_PMSN (PMSNID),
  CONSTRAINT FK_UPM_USER FOREIGN KEY (USERID) REFERENCES SYS_USER (USERID),
  CONSTRAINT FK_UPM_PMSN FOREIGN KEY (PMSNID) REFERENCES SYS_PERMISSION (PMSNID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户权限表';