package com.dyenigma.test.entity;

import java.util.Date;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_ID
     *
     * @mbggenerated
     */
    private Integer coId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_NAME
     *
     * @mbggenerated
     */
    private String coName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_PHONE
     *
     * @mbggenerated
     */
    private String coPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_FAX
     *
     * @mbggenerated
     */
    private String coFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_ADR
     *
     * @mbggenerated
     */
    private String coAdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.ZIP
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CONTACT
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.MANAGER
     *
     * @mbggenerated
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.BANK
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.BANK_ACCT
     *
     * @mbggenerated
     */
    private String bankAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CO_DESC
     *
     * @mbggenerated
     */
    private String coDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_ID
     *
     * @return the value of sys_company.CO_ID
     *
     * @mbggenerated
     */
    public Integer getCoId() {
        return coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_ID
     *
     * @param coId the value for sys_company.CO_ID
     *
     * @mbggenerated
     */
    public void setCoId(Integer coId) {
        this.coId = coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_NAME
     *
     * @return the value of sys_company.CO_NAME
     *
     * @mbggenerated
     */
    public String getCoName() {
        return coName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_NAME
     *
     * @param coName the value for sys_company.CO_NAME
     *
     * @mbggenerated
     */
    public void setCoName(String coName) {
        this.coName = coName == null ? null : coName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_PHONE
     *
     * @return the value of sys_company.CO_PHONE
     *
     * @mbggenerated
     */
    public String getCoPhone() {
        return coPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_PHONE
     *
     * @param coPhone the value for sys_company.CO_PHONE
     *
     * @mbggenerated
     */
    public void setCoPhone(String coPhone) {
        this.coPhone = coPhone == null ? null : coPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_FAX
     *
     * @return the value of sys_company.CO_FAX
     *
     * @mbggenerated
     */
    public String getCoFax() {
        return coFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_FAX
     *
     * @param coFax the value for sys_company.CO_FAX
     *
     * @mbggenerated
     */
    public void setCoFax(String coFax) {
        this.coFax = coFax == null ? null : coFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_ADR
     *
     * @return the value of sys_company.CO_ADR
     *
     * @mbggenerated
     */
    public String getCoAdr() {
        return coAdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_ADR
     *
     * @param coAdr the value for sys_company.CO_ADR
     *
     * @mbggenerated
     */
    public void setCoAdr(String coAdr) {
        this.coAdr = coAdr == null ? null : coAdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.ZIP
     *
     * @return the value of sys_company.ZIP
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.ZIP
     *
     * @param zip the value for sys_company.ZIP
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.SORT
     *
     * @return the value of sys_company.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.SORT
     *
     * @param sort the value for sys_company.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.EMAIL
     *
     * @return the value of sys_company.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.EMAIL
     *
     * @param email the value for sys_company.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CONTACT
     *
     * @return the value of sys_company.CONTACT
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CONTACT
     *
     * @param contact the value for sys_company.CONTACT
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.STATUS
     *
     * @return the value of sys_company.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.STATUS
     *
     * @param status the value for sys_company.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CREATED
     *
     * @return the value of sys_company.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CREATED
     *
     * @param created the value for sys_company.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.LASTMOD
     *
     * @return the value of sys_company.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.LASTMOD
     *
     * @param lastmod the value for sys_company.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.MANAGER
     *
     * @return the value of sys_company.MANAGER
     *
     * @mbggenerated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.MANAGER
     *
     * @param manager the value for sys_company.MANAGER
     *
     * @mbggenerated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.BANK
     *
     * @return the value of sys_company.BANK
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.BANK
     *
     * @param bank the value for sys_company.BANK
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.BANK_ACCT
     *
     * @return the value of sys_company.BANK_ACCT
     *
     * @mbggenerated
     */
    public String getBankAcct() {
        return bankAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.BANK_ACCT
     *
     * @param bankAcct the value for sys_company.BANK_ACCT
     *
     * @mbggenerated
     */
    public void setBankAcct(String bankAcct) {
        this.bankAcct = bankAcct == null ? null : bankAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CO_DESC
     *
     * @return the value of sys_company.CO_DESC
     *
     * @mbggenerated
     */
    public String getCoDesc() {
        return coDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CO_DESC
     *
     * @param coDesc the value for sys_company.CO_DESC
     *
     * @mbggenerated
     */
    public void setCoDesc(String coDesc) {
        this.coDesc = coDesc == null ? null : coDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CREATER
     *
     * @return the value of sys_company.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CREATER
     *
     * @param creater the value for sys_company.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.MODIFYER
     *
     * @return the value of sys_company.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.MODIFYER
     *
     * @param modifyer the value for sys_company.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}