package com.dyenigma.test.entity;

import java.util.Date;

public class Division {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_ID
     *
     * @mbggenerated
     */
    private Integer divId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_NAME
     *
     * @mbggenerated
     */
    private String divName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.MANAGER
     *
     * @mbggenerated
     */
    private Integer manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_PHONE
     *
     * @mbggenerated
     */
    private String divPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.PRNT_ID
     *
     * @mbggenerated
     */
    private Integer prntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_ADR
     *
     * @mbggenerated
     */
    private String divAdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.CO_ID
     *
     * @mbggenerated
     */
    private Integer coId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_DESC
     *
     * @mbggenerated
     */
    private String divDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_division.DIV_ICON
     *
     * @mbggenerated
     */
    private String divIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_ID
     *
     * @return the value of sys_division.DIV_ID
     *
     * @mbggenerated
     */
    public Integer getDivId() {
        return divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_ID
     *
     * @param divId the value for sys_division.DIV_ID
     *
     * @mbggenerated
     */
    public void setDivId(Integer divId) {
        this.divId = divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_NAME
     *
     * @return the value of sys_division.DIV_NAME
     *
     * @mbggenerated
     */
    public String getDivName() {
        return divName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_NAME
     *
     * @param divName the value for sys_division.DIV_NAME
     *
     * @mbggenerated
     */
    public void setDivName(String divName) {
        this.divName = divName == null ? null : divName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.MANAGER
     *
     * @return the value of sys_division.MANAGER
     *
     * @mbggenerated
     */
    public Integer getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.MANAGER
     *
     * @param manager the value for sys_division.MANAGER
     *
     * @mbggenerated
     */
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_PHONE
     *
     * @return the value of sys_division.DIV_PHONE
     *
     * @mbggenerated
     */
    public String getDivPhone() {
        return divPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_PHONE
     *
     * @param divPhone the value for sys_division.DIV_PHONE
     *
     * @mbggenerated
     */
    public void setDivPhone(String divPhone) {
        this.divPhone = divPhone == null ? null : divPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.PRNT_ID
     *
     * @return the value of sys_division.PRNT_ID
     *
     * @mbggenerated
     */
    public Integer getPrntId() {
        return prntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.PRNT_ID
     *
     * @param prntId the value for sys_division.PRNT_ID
     *
     * @mbggenerated
     */
    public void setPrntId(Integer prntId) {
        this.prntId = prntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_ADR
     *
     * @return the value of sys_division.DIV_ADR
     *
     * @mbggenerated
     */
    public String getDivAdr() {
        return divAdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_ADR
     *
     * @param divAdr the value for sys_division.DIV_ADR
     *
     * @mbggenerated
     */
    public void setDivAdr(String divAdr) {
        this.divAdr = divAdr == null ? null : divAdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.CO_ID
     *
     * @return the value of sys_division.CO_ID
     *
     * @mbggenerated
     */
    public Integer getCoId() {
        return coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.CO_ID
     *
     * @param coId the value for sys_division.CO_ID
     *
     * @mbggenerated
     */
    public void setCoId(Integer coId) {
        this.coId = coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_DESC
     *
     * @return the value of sys_division.DIV_DESC
     *
     * @mbggenerated
     */
    public String getDivDesc() {
        return divDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_DESC
     *
     * @param divDesc the value for sys_division.DIV_DESC
     *
     * @mbggenerated
     */
    public void setDivDesc(String divDesc) {
        this.divDesc = divDesc == null ? null : divDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.STATUS
     *
     * @return the value of sys_division.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.STATUS
     *
     * @param status the value for sys_division.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.CREATED
     *
     * @return the value of sys_division.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.CREATED
     *
     * @param created the value for sys_division.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.LASTMOD
     *
     * @return the value of sys_division.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.LASTMOD
     *
     * @param lastmod the value for sys_division.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.CREATER
     *
     * @return the value of sys_division.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.CREATER
     *
     * @param creater the value for sys_division.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.MODIFYER
     *
     * @return the value of sys_division.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.MODIFYER
     *
     * @param modifyer the value for sys_division.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_division.DIV_ICON
     *
     * @return the value of sys_division.DIV_ICON
     *
     * @mbggenerated
     */
    public String getDivIcon() {
        return divIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_division.DIV_ICON
     *
     * @param divIcon the value for sys_division.DIV_ICON
     *
     * @mbggenerated
     */
    public void setDivIcon(String divIcon) {
        this.divIcon = divIcon == null ? null : divIcon.trim();
    }
}