package com.dyenigma.test.entity;

import java.util.Date;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_ID
     *
     * @mbggenerated
     */
    private Integer pmsnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_NAME
     *
     * @mbggenerated
     */
    private String pmsnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PRNT_ID
     *
     * @mbggenerated
     */
    private Integer prntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PRNT_NAME
     *
     * @mbggenerated
     */
    private String prntName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_CODE
     *
     * @mbggenerated
     */
    private String pmsnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_URL
     *
     * @mbggenerated
     */
    private String pmsnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_ICON
     *
     * @mbggenerated
     */
    private String pmsnIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PMSN_DESC
     *
     * @mbggenerated
     */
    private String pmsnDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.IS_LEAF
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.IS_DEFAULT
     *
     * @mbggenerated
     */
    private String isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_ID
     *
     * @return the value of sys_permission.PMSN_ID
     *
     * @mbggenerated
     */
    public Integer getPmsnId() {
        return pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_ID
     *
     * @param pmsnId the value for sys_permission.PMSN_ID
     *
     * @mbggenerated
     */
    public void setPmsnId(Integer pmsnId) {
        this.pmsnId = pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_NAME
     *
     * @return the value of sys_permission.PMSN_NAME
     *
     * @mbggenerated
     */
    public String getPmsnName() {
        return pmsnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_NAME
     *
     * @param pmsnName the value for sys_permission.PMSN_NAME
     *
     * @mbggenerated
     */
    public void setPmsnName(String pmsnName) {
        this.pmsnName = pmsnName == null ? null : pmsnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PRNT_ID
     *
     * @return the value of sys_permission.PRNT_ID
     *
     * @mbggenerated
     */
    public Integer getPrntId() {
        return prntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PRNT_ID
     *
     * @param prntId the value for sys_permission.PRNT_ID
     *
     * @mbggenerated
     */
    public void setPrntId(Integer prntId) {
        this.prntId = prntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PRNT_NAME
     *
     * @return the value of sys_permission.PRNT_NAME
     *
     * @mbggenerated
     */
    public String getPrntName() {
        return prntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PRNT_NAME
     *
     * @param prntName the value for sys_permission.PRNT_NAME
     *
     * @mbggenerated
     */
    public void setPrntName(String prntName) {
        this.prntName = prntName == null ? null : prntName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_CODE
     *
     * @return the value of sys_permission.PMSN_CODE
     *
     * @mbggenerated
     */
    public String getPmsnCode() {
        return pmsnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_CODE
     *
     * @param pmsnCode the value for sys_permission.PMSN_CODE
     *
     * @mbggenerated
     */
    public void setPmsnCode(String pmsnCode) {
        this.pmsnCode = pmsnCode == null ? null : pmsnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.SORT
     *
     * @return the value of sys_permission.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.SORT
     *
     * @param sort the value for sys_permission.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.TYPE
     *
     * @return the value of sys_permission.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.TYPE
     *
     * @param type the value for sys_permission.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.STATUS
     *
     * @return the value of sys_permission.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.STATUS
     *
     * @param status the value for sys_permission.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_URL
     *
     * @return the value of sys_permission.PMSN_URL
     *
     * @mbggenerated
     */
    public String getPmsnUrl() {
        return pmsnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_URL
     *
     * @param pmsnUrl the value for sys_permission.PMSN_URL
     *
     * @mbggenerated
     */
    public void setPmsnUrl(String pmsnUrl) {
        this.pmsnUrl = pmsnUrl == null ? null : pmsnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_ICON
     *
     * @return the value of sys_permission.PMSN_ICON
     *
     * @mbggenerated
     */
    public String getPmsnIcon() {
        return pmsnIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_ICON
     *
     * @param pmsnIcon the value for sys_permission.PMSN_ICON
     *
     * @mbggenerated
     */
    public void setPmsnIcon(String pmsnIcon) {
        this.pmsnIcon = pmsnIcon == null ? null : pmsnIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PMSN_DESC
     *
     * @return the value of sys_permission.PMSN_DESC
     *
     * @mbggenerated
     */
    public String getPmsnDesc() {
        return pmsnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PMSN_DESC
     *
     * @param pmsnDesc the value for sys_permission.PMSN_DESC
     *
     * @mbggenerated
     */
    public void setPmsnDesc(String pmsnDesc) {
        this.pmsnDesc = pmsnDesc == null ? null : pmsnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.IS_LEAF
     *
     * @return the value of sys_permission.IS_LEAF
     *
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.IS_LEAF
     *
     * @param isLeaf the value for sys_permission.IS_LEAF
     *
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.CREATED
     *
     * @return the value of sys_permission.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.CREATED
     *
     * @param created the value for sys_permission.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.LASTMOD
     *
     * @return the value of sys_permission.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.LASTMOD
     *
     * @param lastmod the value for sys_permission.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.CREATER
     *
     * @return the value of sys_permission.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.CREATER
     *
     * @param creater the value for sys_permission.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.MODIFYER
     *
     * @return the value of sys_permission.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.MODIFYER
     *
     * @param modifyer the value for sys_permission.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.IS_DEFAULT
     *
     * @return the value of sys_permission.IS_DEFAULT
     *
     * @mbggenerated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.IS_DEFAULT
     *
     * @param isDefault the value for sys_permission.IS_DEFAULT
     *
     * @mbggenerated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }
}