package com.dyenigma.test.entity;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.POST_ID
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.POST_NAME
     *
     * @mbggenerated
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.DIV_ID
     *
     * @mbggenerated
     */
    private Integer divId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.POST_DESC
     *
     * @mbggenerated
     */
    private String postDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.POST_ID
     *
     * @return the value of sys_post.POST_ID
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.POST_ID
     *
     * @param postId the value for sys_post.POST_ID
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.POST_NAME
     *
     * @return the value of sys_post.POST_NAME
     *
     * @mbggenerated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.POST_NAME
     *
     * @param postName the value for sys_post.POST_NAME
     *
     * @mbggenerated
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.DIV_ID
     *
     * @return the value of sys_post.DIV_ID
     *
     * @mbggenerated
     */
    public Integer getDivId() {
        return divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.DIV_ID
     *
     * @param divId the value for sys_post.DIV_ID
     *
     * @mbggenerated
     */
    public void setDivId(Integer divId) {
        this.divId = divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.POST_DESC
     *
     * @return the value of sys_post.POST_DESC
     *
     * @mbggenerated
     */
    public String getPostDesc() {
        return postDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.POST_DESC
     *
     * @param postDesc the value for sys_post.POST_DESC
     *
     * @mbggenerated
     */
    public void setPostDesc(String postDesc) {
        this.postDesc = postDesc == null ? null : postDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.STATUS
     *
     * @return the value of sys_post.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.STATUS
     *
     * @param status the value for sys_post.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.CREATED
     *
     * @return the value of sys_post.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.CREATED
     *
     * @param created the value for sys_post.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.LASTMOD
     *
     * @return the value of sys_post.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.LASTMOD
     *
     * @param lastmod the value for sys_post.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.CREATER
     *
     * @return the value of sys_post.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.CREATER
     *
     * @param creater the value for sys_post.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.MODIFYER
     *
     * @return the value of sys_post.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.MODIFYER
     *
     * @param modifyer the value for sys_post.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}