package com.dyenigma.test.entity;

import java.util.Date;

public class prjPmsn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.PP_ID
     *
     * @mbggenerated
     */
    private Integer ppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.PRJ_ID
     *
     * @mbggenerated
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    private Integer pmsnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.PP_ID
     *
     * @return the value of sys_prj_pmsn.PP_ID
     *
     * @mbggenerated
     */
    public Integer getPpId() {
        return ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.PP_ID
     *
     * @param ppId the value for sys_prj_pmsn.PP_ID
     *
     * @mbggenerated
     */
    public void setPpId(Integer ppId) {
        this.ppId = ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.PRJ_ID
     *
     * @return the value of sys_prj_pmsn.PRJ_ID
     *
     * @mbggenerated
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.PRJ_ID
     *
     * @param prjId the value for sys_prj_pmsn.PRJ_ID
     *
     * @mbggenerated
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.PMSN_ID
     *
     * @return the value of sys_prj_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    public Integer getPmsnId() {
        return pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.PMSN_ID
     *
     * @param pmsnId the value for sys_prj_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    public void setPmsnId(Integer pmsnId) {
        this.pmsnId = pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.STATUS
     *
     * @return the value of sys_prj_pmsn.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.STATUS
     *
     * @param status the value for sys_prj_pmsn.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.CREATED
     *
     * @return the value of sys_prj_pmsn.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.CREATED
     *
     * @param created the value for sys_prj_pmsn.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.LASTMOD
     *
     * @return the value of sys_prj_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.LASTMOD
     *
     * @param lastmod the value for sys_prj_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.CREATER
     *
     * @return the value of sys_prj_pmsn.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.CREATER
     *
     * @param creater the value for sys_prj_pmsn.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_pmsn.MODIFYER
     *
     * @return the value of sys_prj_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_pmsn.MODIFYER
     *
     * @param modifyer the value for sys_prj_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}