package com.dyenigma.test.entity;

import java.util.Date;

public class PrjUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.PU_ID
     *
     * @mbggenerated
     */
    private Integer puId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.PRJ_ID
     *
     * @mbggenerated
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.LEADER
     *
     * @mbggenerated
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prj_user.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.PU_ID
     *
     * @return the value of sys_prj_user.PU_ID
     *
     * @mbggenerated
     */
    public Integer getPuId() {
        return puId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.PU_ID
     *
     * @param puId the value for sys_prj_user.PU_ID
     *
     * @mbggenerated
     */
    public void setPuId(Integer puId) {
        this.puId = puId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.PRJ_ID
     *
     * @return the value of sys_prj_user.PRJ_ID
     *
     * @mbggenerated
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.PRJ_ID
     *
     * @param prjId the value for sys_prj_user.PRJ_ID
     *
     * @mbggenerated
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.USER_ID
     *
     * @return the value of sys_prj_user.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.USER_ID
     *
     * @param userId the value for sys_prj_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.LEADER
     *
     * @return the value of sys_prj_user.LEADER
     *
     * @mbggenerated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.LEADER
     *
     * @param leader the value for sys_prj_user.LEADER
     *
     * @mbggenerated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.STATUS
     *
     * @return the value of sys_prj_user.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.STATUS
     *
     * @param status the value for sys_prj_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.CREATED
     *
     * @return the value of sys_prj_user.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.CREATED
     *
     * @param created the value for sys_prj_user.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.LASTMOD
     *
     * @return the value of sys_prj_user.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.LASTMOD
     *
     * @param lastmod the value for sys_prj_user.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.CREATER
     *
     * @return the value of sys_prj_user.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.CREATER
     *
     * @param creater the value for sys_prj_user.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prj_user.MODIFYER
     *
     * @return the value of sys_prj_user.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prj_user.MODIFYER
     *
     * @param modifyer the value for sys_prj_user.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}