package com.dyenigma.test.entity;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.PRJ_ID
     *
     * @mbggenerated
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.PRJ_NAME
     *
     * @mbggenerated
     */
    private String prjName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.PRJ_DESC
     *
     * @mbggenerated
     */
    private String prjDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.LEADER
     *
     * @mbggenerated
     */
    private Integer leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.LEVEL
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.PRJ_ID
     *
     * @return the value of sys_project.PRJ_ID
     *
     * @mbggenerated
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.PRJ_ID
     *
     * @param prjId the value for sys_project.PRJ_ID
     *
     * @mbggenerated
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.PRJ_NAME
     *
     * @return the value of sys_project.PRJ_NAME
     *
     * @mbggenerated
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.PRJ_NAME
     *
     * @param prjName the value for sys_project.PRJ_NAME
     *
     * @mbggenerated
     */
    public void setPrjName(String prjName) {
        this.prjName = prjName == null ? null : prjName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.PRJ_DESC
     *
     * @return the value of sys_project.PRJ_DESC
     *
     * @mbggenerated
     */
    public String getPrjDesc() {
        return prjDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.PRJ_DESC
     *
     * @param prjDesc the value for sys_project.PRJ_DESC
     *
     * @mbggenerated
     */
    public void setPrjDesc(String prjDesc) {
        this.prjDesc = prjDesc == null ? null : prjDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.LEADER
     *
     * @return the value of sys_project.LEADER
     *
     * @mbggenerated
     */
    public Integer getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.LEADER
     *
     * @param leader the value for sys_project.LEADER
     *
     * @mbggenerated
     */
    public void setLeader(Integer leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.LEVEL
     *
     * @return the value of sys_project.LEVEL
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.LEVEL
     *
     * @param level the value for sys_project.LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.STATUS
     *
     * @return the value of sys_project.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.STATUS
     *
     * @param status the value for sys_project.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.CREATED
     *
     * @return the value of sys_project.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.CREATED
     *
     * @param created the value for sys_project.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.LASTMOD
     *
     * @return the value of sys_project.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.LASTMOD
     *
     * @param lastmod the value for sys_project.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.CREATER
     *
     * @return the value of sys_project.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.CREATER
     *
     * @param creater the value for sys_project.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.MODIFYER
     *
     * @return the value of sys_project.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.MODIFYER
     *
     * @param modifyer the value for sys_project.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}