package com.dyenigma.test.entity;

import java.util.Date;

public class rolePmsn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.RP_ID
     *
     * @mbggenerated
     */
    private Integer rpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.ROLE_ID
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    private Integer pmsnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.RP_ID
     *
     * @return the value of sys_role_pmsn.RP_ID
     *
     * @mbggenerated
     */
    public Integer getRpId() {
        return rpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.RP_ID
     *
     * @param rpId the value for sys_role_pmsn.RP_ID
     *
     * @mbggenerated
     */
    public void setRpId(Integer rpId) {
        this.rpId = rpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.ROLE_ID
     *
     * @return the value of sys_role_pmsn.ROLE_ID
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.ROLE_ID
     *
     * @param roleId the value for sys_role_pmsn.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.PMSN_ID
     *
     * @return the value of sys_role_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    public Integer getPmsnId() {
        return pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.PMSN_ID
     *
     * @param pmsnId the value for sys_role_pmsn.PMSN_ID
     *
     * @mbggenerated
     */
    public void setPmsnId(Integer pmsnId) {
        this.pmsnId = pmsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.STATUS
     *
     * @return the value of sys_role_pmsn.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.STATUS
     *
     * @param status the value for sys_role_pmsn.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.CREATED
     *
     * @return the value of sys_role_pmsn.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.CREATED
     *
     * @param created the value for sys_role_pmsn.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.LASTMOD
     *
     * @return the value of sys_role_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.LASTMOD
     *
     * @param lastmod the value for sys_role_pmsn.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.CREATER
     *
     * @return the value of sys_role_pmsn.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.CREATER
     *
     * @param creater the value for sys_role_pmsn.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_pmsn.MODIFYER
     *
     * @return the value of sys_role_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_pmsn.MODIFYER
     *
     * @param modifyer the value for sys_role_pmsn.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }
}