package com.dyenigma.test.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.POST_ID
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.DIV_ID
     *
     * @mbggenerated
     */
    private Integer divId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.FIRST_LOGIN
     *
     * @mbggenerated
     */
    private Date firstLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PREV_LOGIN
     *
     * @mbggenerated
     */
    private Date prevLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PREV_IP
     *
     * @mbggenerated
     */
    private String prevIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_COUNT
     *
     * @mbggenerated
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_DESC
     *
     * @mbggenerated
     */
    private String userDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.IS_ONLINE
     *
     * @mbggenerated
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LASTMOD
     *
     * @mbggenerated
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATER
     *
     * @mbggenerated
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.MODIFYER
     *
     * @mbggenerated
     */
    private Integer modifyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ID
     *
     * @return the value of sys_user.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ID
     *
     * @param userId the value for sys_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_NAME
     *
     * @return the value of sys_user.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_NAME
     *
     * @param userName the value for sys_user.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ACCOUNT
     *
     * @return the value of sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ACCOUNT
     *
     * @param account the value for sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.POST_ID
     *
     * @return the value of sys_user.POST_ID
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.POST_ID
     *
     * @param postId the value for sys_user.POST_ID
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.DIV_ID
     *
     * @return the value of sys_user.DIV_ID
     *
     * @mbggenerated
     */
    public Integer getDivId() {
        return divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.DIV_ID
     *
     * @param divId the value for sys_user.DIV_ID
     *
     * @mbggenerated
     */
    public void setDivId(Integer divId) {
        this.divId = divId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PASSWORD
     *
     * @return the value of sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PASSWORD
     *
     * @param password the value for sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param email the value for sys_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param phone the value for sys_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.FIRST_LOGIN
     *
     * @return the value of sys_user.FIRST_LOGIN
     *
     * @mbggenerated
     */
    public Date getFirstLogin() {
        return firstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.FIRST_LOGIN
     *
     * @param firstLogin the value for sys_user.FIRST_LOGIN
     *
     * @mbggenerated
     */
    public void setFirstLogin(Date firstLogin) {
        this.firstLogin = firstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PREV_LOGIN
     *
     * @return the value of sys_user.PREV_LOGIN
     *
     * @mbggenerated
     */
    public Date getPrevLogin() {
        return prevLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PREV_LOGIN
     *
     * @param prevLogin the value for sys_user.PREV_LOGIN
     *
     * @mbggenerated
     */
    public void setPrevLogin(Date prevLogin) {
        this.prevLogin = prevLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PREV_IP
     *
     * @return the value of sys_user.PREV_IP
     *
     * @mbggenerated
     */
    public String getPrevIp() {
        return prevIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PREV_IP
     *
     * @param prevIp the value for sys_user.PREV_IP
     *
     * @mbggenerated
     */
    public void setPrevIp(String prevIp) {
        this.prevIp = prevIp == null ? null : prevIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LAST_LOGIN
     *
     * @return the value of sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LAST_LOGIN
     *
     * @param lastLogin the value for sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_COUNT
     *
     * @return the value of sys_user.LOGIN_COUNT
     *
     * @mbggenerated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_COUNT
     *
     * @param loginCount the value for sys_user.LOGIN_COUNT
     *
     * @mbggenerated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.STATUS
     *
     * @return the value of sys_user.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.STATUS
     *
     * @param status the value for sys_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_DESC
     *
     * @return the value of sys_user.USER_DESC
     *
     * @mbggenerated
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_DESC
     *
     * @param userDesc the value for sys_user.USER_DESC
     *
     * @mbggenerated
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc == null ? null : userDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.IS_ONLINE
     *
     * @return the value of sys_user.IS_ONLINE
     *
     * @mbggenerated
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.IS_ONLINE
     *
     * @param isOnline the value for sys_user.IS_ONLINE
     *
     * @mbggenerated
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATED
     *
     * @return the value of sys_user.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATED
     *
     * @param created the value for sys_user.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LASTMOD
     *
     * @return the value of sys_user.LASTMOD
     *
     * @mbggenerated
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LASTMOD
     *
     * @param lastmod the value for sys_user.LASTMOD
     *
     * @mbggenerated
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATER
     *
     * @return the value of sys_user.CREATER
     *
     * @mbggenerated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATER
     *
     * @param creater the value for sys_user.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.MODIFYER
     *
     * @return the value of sys_user.MODIFYER
     *
     * @mbggenerated
     */
    public Integer getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.MODIFYER
     *
     * @param modifyer the value for sys_user.MODIFYER
     *
     * @mbggenerated
     */
    public void setModifyer(Integer modifyer) {
        this.modifyer = modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SORT
     *
     * @return the value of sys_user.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SORT
     *
     * @param sort the value for sys_user.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}