package com.dyenigma.test.dao;

import com.dyenigma.test.entity.PostRole;

public interface PostRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    int insert(PostRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    int insertSelective(PostRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    PostRole selectByPrimaryKey(Integer prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PostRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PostRole record);
}