package com.dyenigma.test.dao;

import com.dyenigma.test.entity.PrjUser;

public interface PrjUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer puId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    int insert(PrjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    int insertSelective(PrjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    PrjUser selectByPrimaryKey(Integer puId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prj_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrjUser record);
}