package com.dyenigma.test.dao;

import com.dyenigma.test.entity.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer prjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    Project selectByPrimaryKey(Integer prjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project record);
}