package com.dyenigma.test.dao;

import com.dyenigma.test.entity.rolePmsn;

public interface rolePmsnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    int insert(rolePmsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    int insertSelective(rolePmsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    rolePmsn selectByPrimaryKey(Integer rpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(rolePmsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_pmsn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(rolePmsn record);
}