package com.dyenigma.test.dao;

import com.dyenigma.test.entity.UserPost;

public interface UserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    int insert(UserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    int insertSelective(UserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    UserPost selectByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPost record);
}